name: Add IP Region

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Set up environment
      run: |
        echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV
    - name: Run Python script
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: python purchased_cf.py

    - name: Commit and push changes
      #uses: stefanzweifel/git-auto-commit-action@v4
      #with:
      #  commit_message: generate auto
      run: |
        git config --global user.email "action@lxxself.com"
        git config --global user.name "ActionBot"
        git add .
        git commit -m "Update country files"
        git push
